name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: npm run build
      id: npm-run-build
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: npm run build
        setup-command: npm install
        command: npm run build
        timeout: 2
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        NPM-RUN-BUILD_RESULTS: "${{steps.npm-run-build.outputs.result}}"
      with:
        runners: npm-run-build
